### ISSUE TITLE
Feature: Heat Maps

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#216]
**Problem to solve**
 Wir brauchen eine Heat-Map, welche das quantitative Vorkommen stärker visualisiert.
AB Plots do not represent the significance and incidence of a certain color in the plot.

**Solution to the problem**
I would like to have a heat map that represents the incidence of colors in AB Plots as an extention to AB Image and Palette Dot Plots.

**Comment by ghalter** [comment]
See #245
