### ISSUE TITLE
Requirements for Compability with SPUR

### ISSUE THREAD

**Issue by JonathanSchaber** [FilmColors/VIAN#236]
Some unclarities / features to implement:

- Possibility to load predefined Vocabularies (Created in ELAN e.g.)
- Annotation of short clips (~ 1min) must be possible (should already be, according to Wolfgang, there's sometimes a problem...), feature like playing with reduced speed would be nice
- Query local annotated projects
- Exportable format of annotated projects (XML e.g.)
- Subtitles importable as own layer

General:

The automated Features that VIAN offer seem the most promising (automatic segmentation, semantic segmentation etc.), try to improve usability of those (esp. semantic segmentation).

**Comment by ghalter** [comment]
#255

**Comment by ghalter** [comment]
> Possibility to load predefined Vocabularies (Created in ELAN e.g.)
This is already included via the CSV Importer, we could in theory implement an importer specifically for ELAN, this will however be done in another Milestone

> Annotation of short clips (~ 1min) must be possible (should already be, according to Wolfgang, there's sometimes a problem...), feature like playing with reduced speed would be nice
This has been updated. 

> Query local annotated projects
Yes this is here #247, searching in multiple local projects will be a question of reworking the corpus, this is however currently not supported and will take quite a bit of work. 

> Exportable format of annotated projects (XML e.g.)
VIAN supports a CSV exporter, additionally, we WebAnnotation will follow soon, XML will probably not happen in the near future. 

> Subtitles importable as own layer
#246

**Comment by ghalter** [comment]
SRT Import is now implemented: 
cd22b543
