### ISSUE TITLE
"Player" shows 2 frames (one above the other) when stopping 

### ISSUE THREAD

**Issue by megumihayakawa85** [FilmColors/VIAN#302]
**Describe the bug**
When you play the movie file (Open CV), everything is fine, but when you stopp it, player shows 2 (not identical) frames one above the other. It's a bit annoying when you want to look a frame image closely. 

**To Reproduce**
that happens not always but very often, but I'm not sure, under which circumstances it happens. 

**Console Log**
sorry, I don't have it now.

**Expected behavior**
only a current frame is shown.

**Screenshots**
![Anmerkung 2020-06-11 164309](https://user-images.githubusercontent.com/58776405/86380460-5f632d80-bc8c-11ea-86c7-86f719610588.png)
![Anmerkung 2020-06-11 164052](https://user-images.githubusercontent.com/58776405/86380466-625e1e00-bc8c-11ea-99ad-e8d1ae1066af.png)
![Anmerkung 2020-06-11 163844](https://user-images.githubusercontent.com/58776405/86380473-6427e180-bc8c-11ea-911b-e95d03db039b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Additional context**
When I reload a movie, sometimes the problem is solved, but not always. 

Now it happens again, but when I click for example VIAN-symbol at the bottom of the screen to close the window, the double frames are gone and it shows only one frame. very strange... but it happens again, when I move the cursor on the timeline. 

![image](https://user-images.githubusercontent.com/58776405/86385768-1792d500-bc91-11ea-96c5-f6abd3bdc0a8.png)

![Anmerkung 2020-07-02 182421](https://user-images.githubusercontent.com/58776405/86385949-5cb70700-bc91-11ea-9623-de26c9a9fe7b.png)
![image](https://user-images.githubusercontent.com/58776405/86386060-896b1e80-bc91-11ea-9a92-20ff768bc9aa.png)

**Comment by JonathanSchaber** [comment]
As we noticed yesterday, this only happens with OpenCV, not with VLC, and maybe it has something got to do with the .mov format...
