### ISSUE TITLE
Make project folder invisible

### ISSUE THREAD

**Issue by JonathanSchaber** [FilmColors/VIAN#325]
Right now, users can manipulate the structure of a project's folder (e.g. delete screenshot files, delete subfolders copy folders into it et.c). This may lead to unexpected behaviour when users are not completely sure what they are doing (drag-and-dropping between two file explorers etc.).

One possibility to avoid this would be to hide the folders. (Advanced users then may still perform actions on it.)

**Comment by ghalter** [comment]
Currently, some of these folders are kind of historic anyway. 
For VIAN, only the "data" and "export" folder is necessary. 

- The first contains data assets connected to the project, we can easily hide it. 
- **Export** mainly contains data for the Browser Visualizations, we can hide it as well. 
- **Results** can be removed essentially 
- **Shots** is de default export directory for screenshots @flueko this folder necessary, or are screenshots typically exported to another location anyway?
