### ISSUE TITLE
Search for Film After Opening VIAN

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#333]
When opening VIAN an error message appears that it couldn't find the movie when no project is selected yet.

<img width="1736" alt="Screen Shot 2021-01-28 at 09 02 46" src="https://user-images.githubusercontent.com/30805626/106172607-d63fa680-6147-11eb-809e-0b2caf5d75f3.png">
.

**Comment by JonathanSchaber** [comment]
could not reproduce, does this happen always for you @flueko?
