### ISSUE TITLE
Vocabularies in classification bar not shown in Timeline 

### ISSUE THREAD

**Issue by megumihayakawa85** [FilmColors/VIAN#337]
**Describe the bug**
 vocabularies in classification bar are not shown till you click at each bar. I also changed the font size, but it didn't solve the problem. 

**To Reproduce**
1. Open VIAN and then it will not appear. 

**Console Log**
Copy the last 20 lines in the terminal here.

**Expected behavior**
Classification bar with vocabularies are shown in Timeline. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58776405/115748231-4308bc80-a396-11eb-9724-4e5f5b03522c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome]
 - Version []

**Additional context**
VIAN

**Comment by flueko** [comment]
Is this still an issue?
