### ISSUE TITLE
Player is not Showing Video on Play

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#355]
A random still image is shown as soon as the player is turned into the play mode, refreshes only while scrubbing.

https://user-images.githubusercontent.com/30805626/136680144-8f6014c2-cbcb-49ed-9769-9848fe8c5f9b.mov

**Comment by flueko** [comment]
Also several crashes. Here is one report of the last crash.
[VIAN_Crash.docx](https://github.com/ghalter/VIAN/files/7316811/VIAN_Crash.docx)

**Comment by ghalter** [comment]
Could this be a problem with VLC, what kind of movie are you playing? 
Any information about when the crash happens, how to reproduce it?
