### ISSUE TITLE
Screenshot Manager: Too Much Headroom --> Screenshots Not Visible

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#358]
After being produced automatically, the screenshots are not visible in the screenshot manager due to too much headroom / insufficient scaling.

Is it possible to remove the headroom or to display screenshots in total?

**Comment by ghalter** [comment]
Yes, we just discussed that the Screenshot Manager could use an update in general. 

From Slack:  
Ein wiederkehrendes Problem ist es, dass die Nummerierung der Segmentierung im Screenshot Manager anscheinend nicht aktualisiert wird und daher von der Segmentierung in der Timeline abweicht.

**Comment by flueko** [comment]
<img width="1709" alt="Screen Shot 2021-11-04 at 12 27 48" src="https://user-images.githubusercontent.com/30805626/140305971-87b63271-60a9-4316-815e-b39d6e433334.png">
<img width="1707" alt="Screen Shot 2021-11-04 at 12 27 36" src="https://user-images.githubusercontent.com/30805626/140305984-3c0c69bc-3cf5-4e5f-9a52-08f6054e80cb.png">
