### ISSUE TITLE
Dialogue Window Jumps to Back When Adding Project Path on New Project

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#361]
When I open a new project, the dialogue window jumps behind the player and gets visible only when one lowers the player interface.
<img width="1746" alt="Screen Shot 2021-11-04 at 11 38 19" src="https://user-images.githubusercontent.com/30805626/140300281-dc3f0184-7819-4079-a883-d480810d0e27.png">

**Comment by ghalter** [comment]
50487b5d42512344e86ed9b9d857f5121ef9c806

Could somebody test this on macOS?

**Comment by flueko** [comment]
Tested, looking good as well.

**Comment by pascalforny** [comment]
cannot be reproduced anymore. Closing
