### ISSUE TITLE
Two Videos Visible in Player After New Project Has Been Created

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#362]
<img width="1753" alt="Screen Shot 2021-11-04 at 11 41 13" src="https://user-images.githubusercontent.com/30805626/140300920-7f13f79c-f1a8-43b7-a9c4-7cbbe3992074.png">

**Comment by ghalter** [comment]
7d8067d04364367344af4a5e59b55f1d72c7dddf

**Comment by ghalter** [comment]
Could somebody test if this fix works. 
The problem is essentially that a Window resize has to be triggered to syncronize the DrawingOverlay with the Player

**Comment by flueko** [comment]
Tested, was looking good. Thanks.
