### ISSUE TITLE
Crash after installing VIAN (macOS Monterey, M1 chip). VIAN can't be launched.

### ISSUE THREAD

**Issue by sinjabiaa** [FilmColors/VIAN#377]
**Describe the bug**
The App can be installed successfully, but not launched/opened. 

I marked the App in the macOS Monterey (M1 chip) System Preferences as save, but the app can't be opened.
The error message “VIAN quit unexpectedly" pops up. 
Python (via Anaconda) and the VLC Player are installed.

This problem happens to several MacOS users of a film analysis seminar of the University of Jena (Germany).
We would appreciate any online help instructions in order to launch VIAN. Thanks in advance.

**To Reproduce**
1. Go to 'Sytem Preferences'
2. Click on 'Security & Privacy'
3. Click on 'Click the log to make changes'
3. Categorise/Mark VIAN as save App (Checkbox)
4. Close 'System Preferences'
5.  Open 'VIAN'
6. Error report 'VIAN quit unexpectedly'

**Report** (full report please see attachment) 
Translated Report (Full Report Below)
-------------------------------------

Process:               VIAN [91131]
Path:                  /private/var/folders/*/VIAN.app/Contents/MacOS/VIAN
Identifier:            VIAN
Version:               0.0.0 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-11-18 10:46:14.7977 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        CB1548F7-5DAF-4DF6-A7DD-219A0658905A

Sleep/Wake UUID:       EA2A3EDA-47FF-4FF6-A620-4DA56F1DEA78

Time Awake Since Boot: 20000 seconds
Time Since Wake:       2840 seconds

System Integrity Protection: enabled

Notes:
thread_get_state(PAGEIN) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(EXCEPTION) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(FLAVOR) returned 0x10000003: (ipc/send) invalid destination port

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [91131]

Error Formulating Crash Report:
thread_get_state(PAGEIN) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(EXCEPTION) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(FLAVOR) returned 0x10000003: (ipc/send) invalid destination port

**Desktop (please complete the following information):**
 - OS: MacOS Monetery (M1 chip)
 - Browser Safari
 - Version 12.0.1
 -
[Translated Report.pdf](https://github.com/ghalter/VIAN/files/7561924/Translated.Report.pdf)

**Comment by pascalforny** [comment]
Hi sinjabiaa
Thanks for reporting! We are experiencing similar behavior on very recent system. We are currently investigating and we will let you know about a fix hopefully soon!

**Comment by simifilm** [comment]
Doesn't work for me either on M1. I'm on Big Sur though.

**Comment by ghalter** [comment]
As far as I understand, VIAN from Source supports macos M1 architecture in theory. 
I assume the problem lies in the fact that the virtual machine building the OSX version in Github Actions is x64 based. 

The feature request for such VMs seems to be here. 
https://github.com/actions/virtual-environments/issues/2187

A assume for the m1 versions, we currently have no other option than building them manually on a m1 based machine.

**Comment by pascalforny** [comment]
We just released version 0.9.8 (https://github.com/FilmColors/VIAN/releases/tag/0.9.8). This is just a build of the current development status. Please let us know about your feedback.
Alternatively, there is a way to run VIAN directly from source using mambaforge with the requirements in environment-macos.yml. For more detailed instructions, feel free to get in touch again.
