### ISSUE TITLE
Segment No. Missing in Screenshot Manager

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#378]
Segment no. vanishes when working / zooming into the screenshot manager 
![Screen Shot 2021-11-18 at 13 54 42](https://user-images.githubusercontent.com/30805626/142503071-08cf3b87-c7e0-46b1-a4da-08d8bc54473f.png)

**Comment by flueko** [comment]
Has this issue been resolved?

**Comment by flueko** [comment]
#392 #388 same issue?

**Comment by pascalforny** [comment]
develop branch up to18fca250884ccb7406c6abff20923ca22062137d resolves several screenshot manager issues
