### ISSUE TITLE
Scrubbing Not Refreshing

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#380]
During scrubbing the video is often not refreshing (happening with the video 3859_1_1_21Grams_2003, possibly 3859_21Grams_2003 on server).

Could this be a video related issue?

![Screen Shot 2021-11-20 at 23 31 40](https://user-images.githubusercontent.com/30805626/142753763-175acc3d-eea6-4d71-a26e-37b098a8bf02.png)

**Comment by ghalter** [comment]
Here, OpenCV seems tto not be enabled.

**Comment by ghalter** [comment]
We may however thing about a different mechanism. VLC often has quite low update rates, on the other hand, on low performance systems, with a openCV update on can be quite CPU intensive

**Comment by flueko** [comment]
Is this still an issue? Do we have to discuss it?
