### ISSUE TITLE
Error in Calculation of Duration

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#386]
There is an error in the calculation of the duration.
<img width="919" alt="Screen Shot 2021-12-01 at 22 29 08" src="https://user-images.githubusercontent.com/30805626/144370236-b5d2db73-6d34-49fc-8149-0d26a0f94f0a.png">
[Matrix_segmentation.csv](https://github.com/ghalter/VIAN/files/7639557/Matrix_segmentation.csv)

**Comment by flueko** [comment]
Is this still the case?

**Comment by pascalforny** [comment]
Addressed by commit 907464c062ae904f2eb7dbaca6ebd0aed58fdc86 as well
