### ISSUE TITLE
Screenshots not completely displayed 

### ISSUE THREAD

**Issue by megumihayakawa85** [FilmColors/VIAN#388]
**Describe the bug**
All Screenshots cannnot be displayed 

**To Reproduce**
it just happend 

**Console Log**
Copy the last 20 lines in the terminal here.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/58776405/153570677-ce44e67d-8c4a-4983-8a09-27fe163cb88f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - VIAN 0.9.7

**Comment by pascalforny** [comment]
develop branch up to18fca250884ccb7406c6abff20923ca22062137d resolves several screenshot manager issues
