### ISSUE TITLE
Warning on opening VIAN 

### ISSUE THREAD

**Issue by flueko** [FilmColors/VIAN#398]
When I opened VIAN I received a warning.
<img width="417" alt="Screen Shot 2022-09-30 at 11 46 45" src="https://user-images.githubusercontent.com/30805626/193339606-ba00643b-3572-4a37-8dc7-a2283ee2685b.png">

**Comment by retokromer** [comment]
Possibly related to https://github.com/FilmColors/VIAN/issues/385

**Comment by ghalter** [comment]
dup
